services:
  website:
    image: localhost/aloechat-website:latest
    build:
      context: .
      dockerfile: website.dockerfile
    networks:
      - frontend

  backend:
    image: localhost/aloechat-website-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
